const style = {
  cardStyle: {
    borderStyle: "solid",
  },
  availableSlotStyle: {
    display: "flex",
    backgroundColor: "#EBF4F3",
    textAlign: "center",
    cursor: "pointer",
    fontFamily: "Poppins",
    minWidth: "45px",
    minHeight: "45px",
    justifyContent: "center",
    alignItems: "center",
    margin: 0.5,
    fontWeight: 400,
    border: "1px solid #F1F4F3",
    color: "#38A9A5",
    borderRadius: 1,
  },
  notAvailableSlotStyle: {
    display: "flex",
    textAlign: "center",
    cursor: "pointer",
    fontFamily: "Poppins",
    minWidth: "45px",
    minHeight: "45px",
    justifyContent: "center",
    alignItems: "center",
    margin: 0.5,
    fontWeight: 400,
    border: "1px solid #F1F4F3",
    color: "#BEC1C7",
    borderRadius: 1,
  },
  availabilityStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  typographyStyle: {
    fontFamily: "Poppins",
    fontWeight: 300,
  },
};
export default style;
