/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import config from './config/config';
const awsmobile = config.amplifyConfig;
export default awsmobile;
